import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createImageGenerationToolSource } from "../src/connectors/image-generation.ts";
import type { ImageGenerationToolRuntime } from "../src/image-generation.ts";
import { FilesystemArtifactBlobStore } from "../src/storage/artifact-blob-store.ts";
import { openLocalDatabase } from "../src/storage/database.ts";
import { runs, tasks } from "../src/storage/schema.ts";
import { SqliteRunArtifactRepository } from "../src/storage/sqlite-run-artifact-repository.ts";

const cleanup: Array<() => Promise<void> | void> = [];

afterEach(async () => {
  await Promise.allSettled(cleanup.splice(0).map((close) => close()));
});

describe("generate_image tool", () => {
  test("stores generated bytes and returns references only", async () => {
    const local = openLocalDatabase({ filename: ":memory:" });
    cleanup.push(() => local.close());
    insertRun(local.db, "run-image");
    const root = await mkdtemp(join(tmpdir(), "springroll-image-tool-"));
    cleanup.push(() => rm(root, { recursive: true, force: true }));
    const bytes = pngHeader(640, 480);
    const referenceBytes = pngHeader(320, 640);
    const service: ImageGenerationToolRuntime = {
      async listModels() {
        return [
          {
            handle: "openai:gpt-image-2",
            providerId: "openai",
            modelId: "gpt-image-2",
            name: "GPT Image 2",
          },
          {
            handle: "openrouter:google/gemini-image",
            providerId: "openrouter",
            modelId: "google/gemini-image",
            name: "Gemini Image",
          },
        ];
      },
      async generate(input) {
        expect(input).toMatchObject({
          prompt: "A lighthouse in a storm",
          orientation: "landscape",
          model: "openrouter:google/gemini-image",
          references: [{ bytes: referenceBytes, mediaType: "image/png" }],
        });
        return {
          images: [{ bytes, mediaType: "image/png" }],
          providerId: "openai",
          modelId: "gpt-image-2",
          billing: "metered",
          inputTokens: 7,
          outputTokens: 11,
          totalTokens: 18,
          costUsdMicros: 125_000,
          actualCostUsdMicros: 125_000,
          costSource: "provider_reported",
        };
      },
    };
    const blobs = new FilesystemArtifactBlobStore(root);
    const artifacts = new SqliteRunArtifactRepository(local.db);
    const referenceBlob = await blobs.put(referenceBytes);
    const referenceArtifact = artifacts.create({
      owner: { kind: "run", id: "run-image" },
      captureKey: "user-reference",
      origin: "attachment",
      sha256: referenceBlob.sha256,
      mediaType: "image/png",
      byteSize: referenceBlob.byteSize,
      width: 320,
      height: 640,
      title: "Reference image",
    });
    const source = createImageGenerationToolSource({
      generation: service,
      blobs,
      artifacts,
    });
    const session = await source.open({
      connection: {
        id: "builtin-image-generation",
        sourceId: source.id,
        credentialRef: "image-generation-model",
        availableIn: ["local"],
      },
      location: "local",
    });
    const [descriptor] = await session.listTools();
    expect(descriptor?.description).toContain("openrouter:google/gemini-image");
    expect(descriptor?.description).toContain("calls can run in parallel");
    expect(JSON.stringify(descriptor?.inputSchema)).not.toContain(
      "google/gemini-image",
    );

    const result = await session.callTool(
      "generate_image",
      {
        prompt: "A lighthouse in a storm",
        model: "openrouter:google/gemini-image",
        orientation: "landscape",
        title: "Storm light",
        alt: "A lighthouse shining through a coastal storm",
        referenceArtifactIds: [referenceArtifact.id],
      },
      {
        taskId: "task-run-image",
        runId: "run-image",
        toolCallId: "tool-call-image",
      },
    );

    const rows = artifacts.listForRun("run-image");
    expect(rows).toHaveLength(2);
    const artifact = rows.find(
      (candidate) => candidate.captureKey === "tool-call-image:0",
    );
    if (!artifact) throw new Error("Expected a stored image artifact");
    expect(artifact).toMatchObject({
      captureKey: "tool-call-image:0",
      mediaType: "image/png",
      width: 640,
      height: 480,
      title: "Storm light",
      alt: "A lighthouse shining through a coastal storm",
      providerId: "openai",
      modelId: "gpt-image-2",
    });
    expect(await blobs.get(artifact.sha256)).toEqual(bytes);
    expect(result.structuredContent).toEqual({
      artifacts: [
        {
          id: artifact.id,
          kind: "image",
          title: "Storm light",
          mediaType: "image/png",
          payload: {
            sha256: artifact.sha256,
            byteSize: bytes.byteLength,
            origin: "generated",
            width: 640,
            height: 480,
            alt: "A lighthouse shining through a coastal storm",
            providerId: "openai",
            modelId: "gpt-image-2",
          },
        },
      ],
      imageCount: 1,
    });
    expect(result.usage).toEqual({
      operation: "image_generation",
      provider: "openai",
      modelId: "gpt-image-2",
      billing: "metered",
      imageCount: 1,
      inputTokens: 7,
      outputTokens: 11,
      totalTokens: 18,
      costUsdMicros: 125_000,
      actualCostUsdMicros: 125_000,
      costSource: "provider_reported",
    });
    expect(JSON.stringify(result)).not.toContain(
      Buffer.from(bytes).toString("base64"),
    );
  });

  test("rejects bytes that do not match the declared media type", async () => {
    const local = openLocalDatabase({ filename: ":memory:" });
    cleanup.push(() => local.close());
    insertRun(local.db, "run-invalid-image");
    const root = await mkdtemp(join(tmpdir(), "springroll-image-tool-"));
    cleanup.push(() => rm(root, { recursive: true, force: true }));
    const blobs = new FilesystemArtifactBlobStore(root);
    const artifacts = new SqliteRunArtifactRepository(local.db);
    const source = createImageGenerationToolSource({
      generation: {
        async listModels() {
          return [];
        },
        async generate() {
          return {
            images: [
              {
                bytes: new TextEncoder().encode("not an image"),
                mediaType: "image/png",
              },
            ],
            providerId: "openai",
            modelId: "gpt-image-2",
          };
        },
      },
      blobs,
      artifacts,
    });
    const session = await source.open({
      connection: {
        id: "builtin-image-generation",
        sourceId: source.id,
        credentialRef: "image-generation-model",
        availableIn: ["local"],
      },
      location: "local",
    });

    await expect(
      session.callTool(
        "generate_image",
        { prompt: "Invalid" },
        {
          taskId: "task-run-invalid-image",
          runId: "run-invalid-image",
          toolCallId: "tool-call-invalid",
        },
      ),
    ).rejects.toThrow("do not match image/png");
    expect(artifacts.listForRun("run-invalid-image")).toEqual([]);
    expect(await blobs.totalBytes()).toBe(0);
  });
});

function insertRun(
  db: ReturnType<typeof openLocalDatabase>["db"],
  runId: string,
): void {
  const taskId = `task-${runId}`;
  db.insert(tasks)
    .values({
      id: taskId,
      prompt: "Generate an image",
      schedule: "0 9 * * *",
      nextRunAt: new Date("2026-08-20T16:00:00.000Z"),
    })
    .run();
  db.insert(runs)
    .values({
      id: runId,
      taskId,
      scheduledTime: new Date("2026-08-19T16:00:00.000Z"),
      executionLocation: "local",
    })
    .run();
}

function pngHeader(width: number, height: number): Uint8Array {
  const bytes = new Uint8Array(24);
  bytes.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  bytes.set([0x49, 0x48, 0x44, 0x52], 12);
  const view = new DataView(bytes.buffer);
  view.setUint32(16, width);
  view.setUint32(20, height);
  return bytes;
}
